# Generated by Django 3.0.3 on 2020-04-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appropriate_images_depression', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appropriate_images_mania', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appropriate_images_normal', models.TextField(max_length=30)),
            ],
        ),
    ]
