# Generated by Django 3.0.3 on 2020-04-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_filter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depression',
        ),
        migrations.DeleteModel(
            name='Mania',
        ),
        migrations.DeleteModel(
            name='Normal',
        ),
    ]
